// Generated by CoffeeScript 1.7.1
(function() {
  var Weixin, _crypto, _url;

  _url = require('url');

  _crypto = require('crypto');

  Weixin = (function() {
    function Weixin() {}

    Weixin.prototype.contructor = function() {};

    Weixin.prototype.veritySignature = function(req) {
      var arr, echostr, nonce, query, sha1, shasum, signature, str, timestamp;
      query = _url.parse(req.url, true).query;
      signature = query['signature'];
      timestamp = query['timestamp'];
      nonce = query['nonce'];
      echostr = query['echostr'];
      arr = [token, timestamp, nonce];
      str = arr.sort().join('');
      shasum = _crypto.createHash('sha1');
      shasum.update(str);
      sha1 = shasum.digest('hex');
      return sha1 === signature;
    };

    return Weixin;

  })();

  module.exports = Weixin;

}).call(this);
